apiVersion: apps/v1
kind: Deployment
metadata:
     name: nginx-deployment
spec:
   replicas: 2
   selector:
        matchLabels:
              component: web
   template:
      metadata:
          labels:
             component: web
      spec:
        containers:
          - name : nginx
            image: pachagopi/k8s:restart
            ports:
              - containerPort: 80

